# Generated by Django 4.2.23 on 2025-07-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': '對話', 'verbose_name_plural': '對話'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': '訊息', 'verbose_name_plural': '訊息'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='是否已處理'),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='處理時間(秒)'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='對話標題'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='訊息內容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation', verbose_name='對話'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', '使用者'), ('ai', 'AI助手')], max_length=50, verbose_name='發送者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='發送時間'),
        ),
    ]
